export const TYPES = {
  services: {
    CountUsersService: 'CountUsersService',
    CreateUserService: 'CreateUserService',
    CreateManyUsersService: 'CreateManyUsersService',
    FindUsersByCreatedTimeService: 'FindUsersByCreatedTimeService',
    FindUserByIDService: 'FindUserByIDService',
    FindUserByEmailService: 'FindUserByEmailService',
    FindUserEmailDomainService: 'FindUserEmailDomainService',
    FindUserEmailSubdomainService: 'FindUserEmailSubdomainService',
    FindUserEmailSubAndDomainService: 'FindUserEmailSubAndDomainService',
    GetAllUsersService: 'GetAllUsersService',
    UpdateUserService: 'UpdateUserService',
    DeleteUserService: 'DeleteUserService',
  },
  useCases: {
    CountUsersUseCase: 'CountUsersUseCase',
    CreateUserUseCase: 'CreateUserUseCase',
    CreateManyUsersUseCase: 'ICreateManyUsersUseCase',
    GetAllUsersUseCase: 'GetAllUsersUseCase',
    FindUserByIDUseCase: 'FindUserByIDUseCase',
    FindUserByEmailUseCase: 'FindUserByEmailUseCase',
    FindUserEmailDomainUseCase: 'FindUserEmailDomainUseCase',
    FindUserEmailSubdomainUseCase: 'FindUserEmailSubdomainUseCase',
    UpdateUserUseCase: 'UpdateUserUseCase',
    DeleteUserUseCase: 'DeleteUserUseCase',
  },
};
